
spring:
   cloud:
      config:
         server:
            git:
               uri: https://github.com/nksinh51018/config
# default port for eureka server
server:
   port: 8761

# eureka by default will register itself as a client. So, we need to set it to false.
# What's a client server? See other microservices (image, gallery, auth, etc).
eureka:
   client:
      register-with-eureka: false
      fetch-registry: false
management:
   endpoints:
      web:
         exposure:
            include: "*"